# fly.toml app configuration file generated for wordgo on 2025-09-15T12:03:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wordgo'
primary_region = 'lhr'
kill_signal = 'SIGTERM'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'wordgo.fly.dev'
  PORT = '8080'
  BUMBLEBEE_CACHE_DIR = '/app/priv/bumblebee-cache'
  BUMBLEBEE_OFFLINE = 'true'



[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

  [[http_service.checks]]
    type = "http"
    method = "GET"
    path = "/health/readyz"
    interval = "5s"
    timeout = "2s"
    grace_period = "60s"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
